version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    entrypoint: ["./scripts/run-local.sh"]